<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8rVUW3g' shared service.

return $this->privates['.service_locator.8rVUW3g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\StudentController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\StudentController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
], [
    'App\\Controller\\StudentController::index' => '?',
    'App\\Controller\\StudentController:index' => '?',
]);
